#
# ClusterIQ Console Compose deployment file
################################################################################
version: '3.8'

networks:
  cluster_iq:
    driver: bridge

services:
  console:
    image: quay.io/ecosystem-appeng/cluster-iq-console:latest
    container_name: console
    restart: always
    ports:
      - 8080:8080
    environment:
      BACKEND_URL: 'http://api:8080'
    networks:
      - cluster_iq
    healthcheck:
      test: ['CMD', 'curl --silent -f http://console:8080>/dev/null || exit 1']
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
